version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/matsuyoshi30/gomaze
    steps:
      - checkout
      - run: go get -v -u ./...
      - run: make test
